import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;

/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * NewJFrame152.java
 *
 * Created on 17-mar-2014, 18:17:24
 */
/**
 *
 * @author CESARLA
 */
public class NewJFrame152 extends javax.swing.JFrame {
    
    private Connection connection;
    
    /** Creates new form NewJFrame152 */
    public NewJFrame152() {
        initComponents();
        conectar();
        //leerBD();
        //leerEnlaces();
       
        
    }
    
    private void conectar(){
        
        try {

            connection = DriverManager.getConnection("jdbc:mysql://localhost:3307/direcciones_web", "root", "qwerty");
            System.out.println("Conexión correcta");

        } catch (SQLException e) {

            e.printStackTrace();
            
        }
    }
        
        /*private void leerBD(){
            
            try {
                
                PreparedStatement prsSelect = connection.prepareStatement("SELECT * FROM usuarios");
                ResultSet rs = prsSelect.executeQuery();
                
                while(rs.next()){
                    
                    Usuario us = new Usuario();
                    
                    us.setId(rs.getInt("id"));
                    us.setLogin(rs.getString("login"));
                    us.setClave(rs.getString("clave"));
                    System.out.println(us);
                }
                
                
            } catch (SQLException e){
                e.printStackTrace();
            }
        }*/
    
    public  void leerEnlaces(int id){
        
        try {
                
                PreparedStatement prsSelect = connection.prepareStatement("SELECT * FROM enlaces WHERE idLogin = ?");
                prsSelect.setString(1,Integer.toString(id));
                ResultSet rs = prsSelect.executeQuery();
                
                while(rs.next()){
                    
                    Enlaces en = new Enlaces();
                    
                    en.setId(rs.getInt("id"));
                    en.setUrl(rs.getString("url"));
                    en.setTitulo(rs.getString("titulo"));
                    en.setComentario(rs.getString("comentario"));
                    en.setIdLogin(rs.getInt("idLogin"));
                    en.setPrivado(rs.getBoolean("privado"));
                    jTextArea1.append(en.toString());
                }
                
                
            } catch (SQLException e){
                e.printStackTrace();
            }
        
    }
        
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jButton1.setText("Comprobar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 245, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 67, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButton1)
                    .addComponent(jTextField2, javax.swing.GroupLayout.DEFAULT_SIZE, 198, Short.MAX_VALUE)
                    .addComponent(jTextField1))
                .addGap(60, 60, 60))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 337, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(33, 33, 33)
                        .addComponent(jButton1)))
                .addContainerGap(46, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
// TODO add your handling code here:
    
    if(Usuario.Existe(jTextField1.getText(), jTextField2.getText())!= 0){
        System.out.println(Usuario.Existe(jTextField1.getText(), jTextField2.getText()));
        leerEnlaces(Usuario.Existe(jTextField1.getText(), jTextField2.getText()));
        
    } else {
        
        System.out.println("El usuario no existe");
    }
    
    
}//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NewJFrame152.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NewJFrame152.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NewJFrame152.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NewJFrame152.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new NewJFrame152().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    // End of variables declaration//GEN-END:variables
}

class Usuario {
    
    private int id;
    private String login;
    private String clave;

    public String getClave() {
        return clave;
    }

    public void setClave(String clave) {
        this.clave = clave;
    }

    public int getId() {
        return id;
    }

    public void setId(int id) {
        this.id = id;
    }

    public String getLogin() {
        return login;
    }

    public void setLogin(String login) {
        this.login = login;
    }
    
    public String toString(){
        
        return id + " - "  + login + " - " + clave;
    }
    
    public static int Existe(String login,String clave){
        
        Connection connection;
        int existe = 0;
        
        try {
            connection = DriverManager.getConnection("jdbc:mysql://localhost:3307/direcciones_web", "root", "qwerty");
            System.out.println("Conexión correcta");
            PreparedStatement prsEx = connection.prepareStatement("SELECT COUNT(id) as total FROM usuarios WHERE login  = ? and clave = ?");
            prsEx.setString(1, login);
            prsEx.setString(2, clave);
            ResultSet resset = prsEx.executeQuery();
            
            while(resset.next()){
                
                if(resset.getInt("total")== 1){
                    
                    existe = resset.getInt("id");
                    
                    
                } else {
                    
                    
                }
                
            }
        } catch (SQLException e) {
            
            e.printStackTrace();
        }
        
        return existe;
    }
    
    public void guardar(String login,String clave){
        
        Connection connection;
        
        try {
            
            connection = DriverManager.getConnection("jdbc:mysql://localhost:3307/direcciones_web", "root", "qwerty");
            System.out.println("Conexión correcta");
            PreparedStatement prsSe = connection.prepareStatement("SELECT * FROM usuarios WHERE  id = ?");
            PreparedStatement prsUp = connection.prepareStatement("UPDATE usuarios SET id = ?, login = ?, clave = ?");
            PreparedStatement prsIn = connection.prepareStatement("INSERT INTO usuarios VALUES null,?,?");
            
            prsSe.setString(1, Integer.toString(id));
            ResultSet resset = prsSe.executeQuery();
            

                
                if(resset.next()){
                    
                    prsUp.setString(1, Integer.toString(id));
                    prsUp.setString(2, login);
                    prsUp.setString(3, clave);
                    
                } else {
                    
                    prsIn.setString(1, login);
                    prsIn.setString(2, clave);
                }

            
        } catch (SQLException e) {
            e.printStackTrace();
        }
    }
}
    
    



class Enlaces {
    
    private int id;
    private String url;
    private String titulo;
    private String comentario;
    private int idLogin;
    private boolean privado;

    public String getComentario() {
        return comentario;
    }

    public void setComentario(String comentario) {
        this.comentario = comentario;
    }

    public int getId() {
        return id;
    }

    public void setId(int id) {
        this.id = id;
    }

    public int getIdLogin() {
        return idLogin;
    }

    public void setIdLogin(int idLogin) {
        this.idLogin = idLogin;
    }

    public boolean isPrivado() {
        return privado;
    }

    public void setPrivado(boolean privado) {
        this.privado = privado;
    }

    public String getTitulo() {
        return titulo;
    }

    public void setTitulo(String titulo) {
        this.titulo = titulo;
    }

    public String getUrl() {
        return url;
    }

    public void setUrl(String url) {
        this.url = url;
    }
    
    public String toString(){
        
        return id + " - "  + url + " - " + titulo + " - " + comentario + " - " + idLogin + " - " + privado;
    }
    
}